PROBLEMS = [
    {
        "id": 1,
        "title": "Hello, World!",
        "category": "기초 출력",
        "difficulty": "쉬움",
        "description": "화면에 `Hello, World!`를 출력하세요.",
        "examples": [{"input": "", "output": "Hello, World!"}],
        "test_cases": [{"input": "", "output": "Hello, World!"}],
        "hint": "print() 함수를 사용하세요.",
        "starter_code": "# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 2,
        "title": "두 수의 합",
        "category": "사칙연산",
        "difficulty": "쉬움",
        "description": "두 정수 a, b를 각각 한 줄씩 입력받아 합을 출력하세요.",
        "examples": [{"input": "3\n5", "output": "8"}],
        "test_cases": [
            {"input": "3\n5", "output": "8"},
            {"input": "10\n20", "output": "30"},
            {"input": "-5\n3", "output": "-2"},
        ],
        "hint": "input()으로 받고 int()로 변환하세요.",
        "starter_code": "a = int(input())\nb = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 3,
        "title": "두 수의 곱",
        "category": "사칙연산",
        "difficulty": "쉬움",
        "description": "두 정수 a, b를 각각 한 줄씩 입력받아 곱을 출력하세요.",
        "examples": [{"input": "4\n6", "output": "24"}],
        "test_cases": [
            {"input": "4\n6", "output": "24"},
            {"input": "7\n8", "output": "56"},
            {"input": "-3\n5", "output": "-15"},
        ],
        "hint": "곱셈 연산자 *를 사용하세요.",
        "starter_code": "a = int(input())\nb = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 4,
        "title": "몫과 나머지",
        "category": "사칙연산",
        "difficulty": "쉬움",
        "description": "두 정수 a, b를 입력받아 a를 b로 나눈 **몫**과 **나머지**를 공백으로 구분해 한 줄에 출력하세요.",
        "examples": [{"input": "7\n3", "output": "2 1"}],
        "test_cases": [
            {"input": "7\n3", "output": "2 1"},
            {"input": "10\n4", "output": "2 2"},
            {"input": "15\n5", "output": "3 0"},
        ],
        "hint": "// 연산자(몫), % 연산자(나머지)를 사용하세요.",
        "starter_code": "a = int(input())\nb = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 5,
        "title": "세 수의 평균",
        "category": "사칙연산",
        "difficulty": "쉬움",
        "description": "세 정수 a, b, c를 각각 한 줄씩 입력받아 평균을 소수점 둘째 자리까지 출력하세요.",
        "examples": [{"input": "10\n20\n30", "output": "20.00"}],
        "test_cases": [
            {"input": "10\n20\n30", "output": "20.00"},
            {"input": "1\n2\n3", "output": "2.00"},
            {"input": "5\n10\n15", "output": "10.00"},
        ],
        "hint": "f\"{avg:.2f}\" 형식으로 출력하세요.",
        "starter_code": "a = int(input())\nb = int(input())\nc = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 6,
        "title": "최댓값 구하기",
        "category": "조건문",
        "difficulty": "쉬움",
        "description": "세 정수를 각각 한 줄씩 입력받아 가장 큰 수를 출력하세요.",
        "examples": [{"input": "3\n7\n2", "output": "7"}],
        "test_cases": [
            {"input": "3\n7\n2", "output": "7"},
            {"input": "10\n5\n8", "output": "10"},
            {"input": "-1\n-3\n-2", "output": "-1"},
        ],
        "hint": "max() 함수 또는 if문을 사용하세요.",
        "starter_code": "a = int(input())\nb = int(input())\nc = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 7,
        "title": "짝수와 홀수",
        "category": "조건문",
        "difficulty": "쉬움",
        "description": "정수 n을 입력받아 짝수이면 `짝수`, 홀수이면 `홀수`를 출력하세요.",
        "examples": [
            {"input": "4", "output": "짝수"},
            {"input": "7", "output": "홀수"},
        ],
        "test_cases": [
            {"input": "4", "output": "짝수"},
            {"input": "7", "output": "홀수"},
            {"input": "0", "output": "짝수"},
        ],
        "hint": "% 2 == 0이면 짝수입니다.",
        "starter_code": "n = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 8,
        "title": "절댓값",
        "category": "조건문",
        "difficulty": "쉬움",
        "description": "정수 n을 입력받아 절댓값을 출력하세요.",
        "examples": [{"input": "-5", "output": "5"}],
        "test_cases": [
            {"input": "-5", "output": "5"},
            {"input": "3", "output": "3"},
            {"input": "0", "output": "0"},
        ],
        "hint": "abs() 함수를 사용하거나 if문으로 직접 구현해보세요.",
        "starter_code": "n = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 9,
        "title": "1부터 N까지의 합",
        "category": "반복문",
        "difficulty": "보통",
        "description": "정수 N을 입력받아 1부터 N까지의 합을 출력하세요.",
        "examples": [{"input": "5", "output": "15"}],
        "test_cases": [
            {"input": "5", "output": "15"},
            {"input": "10", "output": "55"},
            {"input": "100", "output": "5050"},
        ],
        "hint": "for i in range(1, N+1) 반복문 또는 N*(N+1)//2 공식을 사용하세요.",
        "starter_code": "n = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 10,
        "title": "1부터 N까지 짝수의 합",
        "category": "반복문",
        "difficulty": "보통",
        "description": "정수 N을 입력받아 1부터 N까지 짝수의 합을 출력하세요.",
        "examples": [{"input": "10", "output": "30"}],
        "test_cases": [
            {"input": "10", "output": "30"},
            {"input": "5", "output": "6"},
            {"input": "20", "output": "110"},
        ],
        "hint": "range(2, N+1, 2) 또는 i % 2 == 0 조건을 사용하세요.",
        "starter_code": "n = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 11,
        "title": "구구단 출력",
        "category": "반복문",
        "difficulty": "보통",
        "description": "정수 N(2~9)을 입력받아 N단 구구단을 출력하세요.\n\n출력 형식: `N x i = 결과` (i는 1부터 9까지)",
        "examples": [{"input": "3", "output": "3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27"}],
        "test_cases": [
            {"input": "3", "output": "3 x 1 = 3\n3 x 2 = 6\n3 x 3 = 9\n3 x 4 = 12\n3 x 5 = 15\n3 x 6 = 18\n3 x 7 = 21\n3 x 8 = 24\n3 x 9 = 27"},
            {"input": "5", "output": "5 x 1 = 5\n5 x 2 = 10\n5 x 3 = 15\n5 x 4 = 20\n5 x 5 = 25\n5 x 6 = 30\n5 x 7 = 35\n5 x 8 = 40\n5 x 9 = 45"},
        ],
        "hint": "for i in range(1, 10) 반복문과 print(f\"{n} x {i} = {n*i}\")를 사용하세요.",
        "starter_code": "n = int(input())\nfor i in range(1, 10):\n    # 여기에 코드를 작성하세요\n    pass\n",
    },
    {
        "id": 12,
        "title": "팩토리얼",
        "category": "반복문",
        "difficulty": "보통",
        "description": "정수 N(0 이상)을 입력받아 N!(팩토리얼)을 출력하세요.\n\n(0! = 1, 1! = 1, 2! = 2, 3! = 6, ...)",
        "examples": [{"input": "5", "output": "120"}],
        "test_cases": [
            {"input": "5", "output": "120"},
            {"input": "0", "output": "1"},
            {"input": "10", "output": "3628800"},
        ],
        "hint": "result = 1로 시작해서 1부터 N까지 곱하세요.",
        "starter_code": "n = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 13,
        "title": "피보나치 수열",
        "category": "반복문",
        "difficulty": "보통",
        "description": "정수 N을 입력받아 피보나치 수열의 N번째 수를 출력하세요.\n\n(1번째=1, 2번째=1, 3번째=2, 4번째=3, 5번째=5, ...)",
        "examples": [{"input": "7", "output": "13"}],
        "test_cases": [
            {"input": "7", "output": "13"},
            {"input": "1", "output": "1"},
            {"input": "10", "output": "55"},
        ],
        "hint": "a, b = 1, 1로 시작해서 a, b = b, a+b를 반복하세요.",
        "starter_code": "n = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 14,
        "title": "소수 판별",
        "category": "조건문",
        "difficulty": "보통",
        "description": "정수 N(2 이상)을 입력받아 소수이면 `소수`, 아니면 `소수 아님`을 출력하세요.",
        "examples": [
            {"input": "7", "output": "소수"},
            {"input": "10", "output": "소수 아님"},
        ],
        "test_cases": [
            {"input": "7", "output": "소수"},
            {"input": "10", "output": "소수 아님"},
            {"input": "2", "output": "소수"},
            {"input": "9", "output": "소수 아님"},
        ],
        "hint": "2부터 N-1까지 나누어 떨어지는 수가 있으면 소수가 아닙니다.",
        "starter_code": "n = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 15,
        "title": "문자열 뒤집기",
        "category": "문자열",
        "difficulty": "쉬움",
        "description": "문자열을 입력받아 뒤집어서 출력하세요.",
        "examples": [{"input": "hello", "output": "olleh"}],
        "test_cases": [
            {"input": "hello", "output": "olleh"},
            {"input": "python", "output": "nohtyp"},
            {"input": "abcde", "output": "edcba"},
        ],
        "hint": "슬라이싱 s[::-1]을 사용하세요.",
        "starter_code": "s = input()\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 16,
        "title": "대문자 변환",
        "category": "문자열",
        "difficulty": "쉬움",
        "description": "영어 문자열을 입력받아 모두 대문자로 변환해 출력하세요.",
        "examples": [{"input": "hello world", "output": "HELLO WORLD"}],
        "test_cases": [
            {"input": "hello world", "output": "HELLO WORLD"},
            {"input": "python", "output": "PYTHON"},
            {"input": "abc123", "output": "ABC123"},
        ],
        "hint": ".upper() 메서드를 사용하세요.",
        "starter_code": "s = input()\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 17,
        "title": "문자 개수 세기",
        "category": "문자열",
        "difficulty": "보통",
        "description": "첫 줄에 문자열, 둘째 줄에 찾을 문자를 입력받아 그 문자가 몇 번 등장하는지 출력하세요.",
        "examples": [{"input": "banana\na", "output": "3"}],
        "test_cases": [
            {"input": "banana\na", "output": "3"},
            {"input": "hello\nl", "output": "2"},
            {"input": "python\nx", "output": "0"},
        ],
        "hint": ".count() 메서드를 사용하세요.",
        "starter_code": "s = input()\nc = input()\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 18,
        "title": "리스트 최솟값과 최댓값",
        "category": "리스트",
        "difficulty": "보통",
        "description": "첫 줄에 정수 N, 다음 줄에 N개의 정수를 공백으로 구분해 입력받아 최솟값과 최댓값을 공백으로 구분해 출력하세요.",
        "examples": [{"input": "5\n3 1 4 1 5", "output": "1 5"}],
        "test_cases": [
            {"input": "5\n3 1 4 1 5", "output": "1 5"},
            {"input": "3\n10 20 30", "output": "10 30"},
            {"input": "4\n-3 -1 -5 -2", "output": "-5 -1"},
        ],
        "hint": "min()과 max() 함수를 사용하세요.",
        "starter_code": "n = int(input())\nnums = list(map(int, input().split()))\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 19,
        "title": "최대공약수",
        "category": "알고리즘",
        "difficulty": "어려움",
        "description": "두 정수 a, b를 입력받아 최대공약수(GCD)를 출력하세요.",
        "examples": [{"input": "12\n8", "output": "4"}],
        "test_cases": [
            {"input": "12\n8", "output": "4"},
            {"input": "36\n24", "output": "12"},
            {"input": "7\n5", "output": "1"},
        ],
        "hint": "유클리드 호제법: gcd(a, b) = gcd(b, a % b), b가 0이면 a가 GCD",
        "starter_code": "a = int(input())\nb = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 20,
        "title": "별 삼각형",
        "category": "반복문",
        "difficulty": "보통",
        "description": "정수 N을 입력받아 N줄짜리 별 삼각형을 출력하세요.\n\n1줄에 *, 2줄에 **, ..., N줄에 ***...* 형식으로 출력하세요.",
        "examples": [{"input": "4", "output": "*\n**\n***\n****"}],
        "test_cases": [
            {"input": "4", "output": "*\n**\n***\n****"},
            {"input": "3", "output": "*\n**\n***"},
            {"input": "1", "output": "*"},
        ],
        "hint": "for i in range(1, N+1): print('*' * i)를 사용하세요.",
        "starter_code": "n = int(input())\n# 여기에 코드를 작성하세요\n",
    },
    # ── 01단원: 출력하기 ──────────────────────────────────────────
    {
        "id": 21,
        "title": "숫자 출력하기",
        "category": "기초 출력",
        "difficulty": "쉬움",
        "description": "다음을 출력하세요.\n\n```\n1994\n```\n\n💡 숫자는 따옴표 없이 print()에 직접 넣을 수 있습니다.",
        "examples": [{"input": "", "output": "1994"}],
        "test_cases": [{"input": "", "output": "1994"}],
        "hint": "print(1994) 처럼 숫자를 따옴표 없이 넣어도 되고, print('1994')처럼 문자열로 넣어도 됩니다.",
        "starter_code": "# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 22,
        "title": "Hello World 출력",
        "category": "기초 출력",
        "difficulty": "쉬움",
        "description": "다음을 출력하세요.\n\n```\nHello World\n```",
        "examples": [{"input": "", "output": "Hello World"}],
        "test_cases": [{"input": "", "output": "Hello World"}],
        "hint": "print() 함수 안에 문자열을 따옴표로 감싸서 출력하세요.",
        "starter_code": "# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 23,
        "title": "두 줄 출력 (print 1번만)",
        "category": "기초 출력",
        "difficulty": "쉬움",
        "description": "다음을 출력하세요. **단, print() 함수를 딱 한 번만 사용하세요.**\n\n```\nHello\nWorld\n```",
        "examples": [{"input": "", "output": "Hello\nWorld"}],
        "test_cases": [{"input": "", "output": "Hello\nWorld"}],
        "hint": "문자열 안에서 줄바꿈은 \\n을 사용합니다. 예: print(\"Hello\\nWorld\")",
        "starter_code": "# print()를 한 번만 사용하세요\n",
    },
    {
        "id": 24,
        "title": "작은따옴표 포함 출력",
        "category": "기초 출력",
        "difficulty": "쉬움",
        "description": "다음을 출력하세요. (출력 결과에 작은따옴표가 포함됩니다)\n\n```\n'Hello World'\n```",
        "examples": [{"input": "", "output": "'Hello World'"}],
        "test_cases": [{"input": "", "output": "'Hello World'"}],
        "hint": "문자열을 큰따옴표(\")로 감싸면 안에서 작은따옴표를 그대로 쓸 수 있습니다.",
        "starter_code": "# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 25,
        "title": "큰따옴표 포함 출력",
        "category": "기초 출력",
        "difficulty": "쉬움",
        "description": '다음을 출력하세요. (출력 결과에 큰따옴표가 포함됩니다)\n\n```\n"Hello World"\n```',
        "examples": [{"input": "", "output": '"Hello World"'}],
        "test_cases": [{"input": "", "output": '"Hello World"'}],
        "hint": "문자열을 작은따옴표(')로 감싸거나, 이스케이프 문자 \\\"를 사용하세요.",
        "starter_code": "# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 26,
        "title": "특수문자 경로 출력",
        "category": "기초 출력",
        "difficulty": "보통",
        "description": "다음을 출력하세요. (역슬래시, 큰따옴표, 작은따옴표가 모두 포함)\n\n```\n\"C:\\Download\\'hello'.py\"\n```\n\n💡 이스케이프 문자: `\\\\` → `\\`, `\\'` → `'`, `\\\"` → `\"`",
        "examples": [{"input": "", "output": '"C:\\Download\\\'hello\'.py"'}],
        "test_cases": [{"input": "", "output": '"C:\\Download\\\'hello\'.py"'}],
        "hint": "이스케이프 문자를 조합하거나, 큰따옴표·작은따옴표를 섞어 사용해보세요.",
        "starter_code": "# 이스케이프 문자를 활용하세요\n",
    },
    # ── 02단원: 자료형 기초 ──────────────────────────────────────
    {
        "id": 27,
        "title": "문자열 자료형 확인",
        "category": "자료형",
        "difficulty": "쉬움",
        "description": "다음 코드를 입력하고 실행하여 `'Coding'`의 자료형을 확인하세요.\n\n```python\nprint(type('Coding'))\n```\n\n💡 `type()` 함수는 값의 **자료형(Data Type)**을 알려줍니다.",
        "examples": [{"input": "", "output": "<class 'str'>"}],
        "test_cases": [{"input": "", "output": "<class 'str'>"}],
        "hint": "위 코드를 그대로 입력하고 실행하세요. 문자열은 str(string)입니다.",
        "starter_code": "# type() 함수로 'Coding'의 자료형을 출력하세요\n",
    },
    {
        "id": 28,
        "title": "정수 자료형 확인",
        "category": "자료형",
        "difficulty": "쉬움",
        "description": "다음 코드를 입력하고 실행하여 정수 `7`의 자료형을 확인하세요.\n\n```python\nprint(type(7))\n```",
        "examples": [{"input": "", "output": "<class 'int'>"}],
        "test_cases": [{"input": "", "output": "<class 'int'>"}],
        "hint": "정수(integer)의 자료형 이름은 int입니다.",
        "starter_code": "# type() 함수로 7의 자료형을 출력하세요\n",
    },
    {
        "id": 29,
        "title": "실수 자료형 확인",
        "category": "자료형",
        "difficulty": "쉬움",
        "description": "다음 코드를 입력하고 실행하여 실수 `3.14`의 자료형을 확인하세요.\n\n```python\nprint(type(3.14))\n```",
        "examples": [{"input": "", "output": "<class 'float'>"}],
        "test_cases": [{"input": "", "output": "<class 'float'>"}],
        "hint": "실수(소수점이 있는 수)의 자료형 이름은 float입니다.",
        "starter_code": "# type() 함수로 3.14의 자료형을 출력하세요\n",
    },
    {
        "id": 30,
        "title": "'5'와 5의 자료형 차이",
        "category": "자료형",
        "difficulty": "쉬움",
        "description": "따옴표로 감싼 `'5'`의 자료형을 확인하세요.\n\n```python\nprint(type('5'))\n```\n\n🤔 숫자처럼 보이지만 따옴표로 감싸면 자료형이 달라집니다!",
        "examples": [{"input": "", "output": "<class 'str'>"}],
        "test_cases": [{"input": "", "output": "<class 'str'>"}],
        "hint": "따옴표로 감싼 '5'는 숫자가 아닌 문자열(str)입니다. type(5)와 비교해보세요!",
        "starter_code": "# type('5')를 출력하고 type(5)와 비교해보세요\n",
    },
    # ── 03단원: 변수 ──────────────────────────────────────────────
    {
        "id": 31,
        "title": "변수에 문자 저장 후 출력",
        "category": "변수",
        "difficulty": "쉬움",
        "description": "변수 `a`에 문자 `'k'`를 저장한 후, 변수를 출력하세요.\n\n```\nk\n```",
        "examples": [{"input": "", "output": "k"}],
        "test_cases": [{"input": "", "output": "k"}],
        "hint": "a = 'k'로 저장하고, print(a)로 출력하세요.",
        "starter_code": "# 변수 a에 'k'를 저장하고 출력하세요\n",
    },
    {
        "id": 32,
        "title": "변수에 정수 저장 후 출력",
        "category": "변수",
        "difficulty": "쉬움",
        "description": "변수 `b`에 숫자 `3`을 저장한 후, 변수를 출력하세요.\n\n```\n3\n```",
        "examples": [{"input": "", "output": "3"}],
        "test_cases": [{"input": "", "output": "3"}],
        "hint": "b = 3으로 저장하고, print(b)로 출력하세요.",
        "starter_code": "# 변수 b에 3을 저장하고 출력하세요\n",
    },
    {
        "id": 33,
        "title": "변수에 실수 저장 후 출력",
        "category": "변수",
        "difficulty": "쉬움",
        "description": "변수 `c`에 실수 `7.34`를 저장한 후, 변수를 출력하세요.\n\n```\n7.34\n```",
        "examples": [{"input": "", "output": "7.34"}],
        "test_cases": [{"input": "", "output": "7.34"}],
        "hint": "c = 7.34로 저장하고, print(c)로 출력하세요.",
        "starter_code": "# 변수 c에 7.34를 저장하고 출력하세요\n",
    },
    {
        "id": 34,
        "title": "두 변수에 서로 다른 자료형 저장 후 출력",
        "category": "변수",
        "difficulty": "쉬움",
        "description": "변수 `a`에 문자 `'c'`, 변수 `b`에 숫자 `5`를 저장한 후, 각각 출력하세요.\n\n```\nc\n5\n```",
        "examples": [{"input": "", "output": "c\n5"}],
        "test_cases": [{"input": "", "output": "c\n5"}],
        "hint": "a = 'c', b = 5로 저장하고 print(a), print(b)를 차례로 쓰세요.",
        "starter_code": "# 변수 a에 'c', b에 5를 저장하고 각각 출력하세요\n",
    },
    {
        "id": 35,
        "title": "다중 변수 한 줄 할당 후 출력",
        "category": "변수",
        "difficulty": "쉬움",
        "description": "**한 줄**로 변수 `a, b, c, d, e`에 `1, 2, 3, 4, 5`를 저장한 후 각각 출력하세요.\n\n```\n1\n2\n3\n4\n5\n```\n\n**힌트 코드:** `a, b, c, d, e = 1, 2, 3, 4, 5`",
        "examples": [{"input": "", "output": "1\n2\n3\n4\n5"}],
        "test_cases": [{"input": "", "output": "1\n2\n3\n4\n5"}],
        "hint": "a, b, c, d, e = 1, 2, 3, 4, 5 로 한 번에 여러 변수에 값을 저장할 수 있습니다!",
        "starter_code": "a, b, c, d, e = 1, 2, 3, 4, 5\n# 각 변수를 순서대로 출력하세요\n",
    },
    {
        "id": 36,
        "title": "변수를 5번 출력하기",
        "category": "변수",
        "difficulty": "쉬움",
        "description": "변수 `num`에 `3`을 저장한 후, 변수를 **5번** 출력하세요.\n\n```\n3\n3\n3\n3\n3\n```",
        "examples": [{"input": "", "output": "3\n3\n3\n3\n3"}],
        "test_cases": [{"input": "", "output": "3\n3\n3\n3\n3"}],
        "hint": "print(num)을 5번 반복하거나, for문을 사용해도 됩니다.",
        "starter_code": "num = 3\n# num을 5번 출력하세요\n",
    },
    {
        "id": 37,
        "title": "두 변수 순서 바꿔 출력",
        "category": "변수",
        "difficulty": "쉬움",
        "description": "변수 `a`에 `1`, 변수 `b`에 `2`를 저장한 후, **b를 먼저, a를 나중에** 출력하세요.\n\n```\n2\n1\n```",
        "examples": [{"input": "", "output": "2\n1"}],
        "test_cases": [{"input": "", "output": "2\n1"}],
        "hint": "print(b)를 먼저 쓰고, 그 다음 print(a)를 쓰세요.",
        "starter_code": "a = 1\nb = 2\n# b를 먼저, a를 나중에 출력하세요\n",
    },
    # ── 04단원: 문자열 포맷 코드 ─────────────────────────────────
    {
        "id": 38,
        "title": "%s 포맷 코드로 문자 출력",
        "category": "포맷 코드",
        "difficulty": "쉬움",
        "description": "변수 `a`에 `'k'`를 저장한 후, **%s 포맷 코드**를 활용하여 출력하세요.\n\n```\nk\n```\n\n💡 `%s`는 **s**tring(문자열) 자리를 나타냅니다.",
        "examples": [{"input": "", "output": "k"}],
        "test_cases": [{"input": "", "output": "k"}],
        "hint": "print('%s' %a) 형식으로 출력하세요.",
        "starter_code": "a = 'k'\n# %s 포맷 코드를 사용해서 a를 출력하세요\n",
    },
    {
        "id": 39,
        "title": "%d 포맷 코드로 정수 출력",
        "category": "포맷 코드",
        "difficulty": "쉬움",
        "description": "변수 `b`에 `3`을 저장한 후, **%d 포맷 코드**를 활용하여 출력하세요.\n\n```\n3\n```\n\n💡 `%d`는 **d**igit(정수) 자리를 나타냅니다.",
        "examples": [{"input": "", "output": "3"}],
        "test_cases": [{"input": "", "output": "3"}],
        "hint": "print('%d' %b) 형식으로 출력하세요.",
        "starter_code": "b = 3\n# %d 포맷 코드를 사용해서 b를 출력하세요\n",
    },
    {
        "id": 40,
        "title": "%f 포맷 코드로 실수 출력",
        "category": "포맷 코드",
        "difficulty": "쉬움",
        "description": "변수 `k`에 `2.362`를 저장한 후, **%f 포맷 코드**를 활용하여 출력하세요.\n\n```\n2.362000\n```\n\n💡 `%f`는 **f**loat(실수) 자리이며, 기본적으로 소수점 **6자리**까지 출력됩니다.",
        "examples": [{"input": "", "output": "2.362000"}],
        "test_cases": [{"input": "", "output": "2.362000"}],
        "hint": "print('%f' %k) 형식으로 출력하세요.",
        "starter_code": "k = 2.362\n# %f 포맷 코드를 사용해서 k를 출력하세요\n",
    },
    {
        "id": 41,
        "title": "%s와 %d 함께 사용하기",
        "category": "포맷 코드",
        "difficulty": "쉬움",
        "description": "변수 `a`에 `'hi'`, `b`에 `5`를 저장한 후, 포맷 코드를 활용하여 다음과 같이 출력하세요.\n\n```\nhi 5\n```",
        "examples": [{"input": "", "output": "hi 5"}],
        "test_cases": [{"input": "", "output": "hi 5"}],
        "hint": "print('%s %d' %(a, b)) 형식으로 여러 포맷 코드를 함께 사용할 수 있습니다.",
        "starter_code": "a = 'hi'\nb = 5\n# 포맷 코드를 사용해서 출력하세요\n",
    },
    {
        "id": 42,
        "title": "나이 출력하기 (포맷 코드)",
        "category": "포맷 코드",
        "difficulty": "쉬움",
        "description": "변수 `n`에 `17`을 저장한 후, 포맷 코드를 활용하여 다음과 같이 출력하세요.\n\n```\n저의 나이는 17살 입니다.\n```",
        "examples": [{"input": "", "output": "저의 나이는 17살 입니다."}],
        "test_cases": [{"input": "", "output": "저의 나이는 17살 입니다."}],
        "hint": "print('저의 나이는 %d살 입니다.' %n) 형식으로 출력하세요.",
        "starter_code": "n = 17\n# 포맷 코드를 사용해서 출력하세요\n",
    },
    {
        "id": 43,
        "title": "이름과 형용사 출력 (포맷 코드)",
        "category": "포맷 코드",
        "difficulty": "쉬움",
        "description": "변수 `name`에 `'홍길동'`, `good`에 `'잘'`을 저장한 후, 포맷 코드를 활용하여 다음과 같이 출력하세요.\n\n```\n홍길동은 잘생겼다\n```",
        "examples": [{"input": "", "output": "홍길동은 잘생겼다"}],
        "test_cases": [{"input": "", "output": "홍길동은 잘생겼다"}],
        "hint": "print('%s은 %s생겼다' %(name, good)) 형식으로 출력하세요.",
        "starter_code": "name = '홍길동'\ngood = '잘'\n# 포맷 코드를 사용해서 출력하세요\n",
    },
    {
        "id": 44,
        "title": "소수점 1자리 반올림 출력",
        "category": "포맷 코드",
        "difficulty": "보통",
        "description": "변수 `k`에 `2.362`를 저장한 후, 포맷 코드를 활용하여 **소수점 첫째 자리까지** 반올림하여 출력하세요.\n\n```\n2.4\n```",
        "examples": [{"input": "", "output": "2.4"}],
        "test_cases": [{"input": "", "output": "2.4"}],
        "hint": "%.1f를 사용하면 소수점 1자리까지 출력됩니다. print('%.1f' %k)",
        "starter_code": "k = 2.362\n# %.1f 포맷 코드를 사용해서 출력하세요\n",
    },
    {
        "id": 45,
        "title": "다양한 %f 포맷 출력",
        "category": "포맷 코드",
        "difficulty": "보통",
        "description": "다음 코드를 그대로 입력하고 실행하여 다양한 실수 포맷 출력을 확인하세요.\n\n```python\na = 3.141592\nprint('1번: %20f' %a)\nprint('2번: %020f' %a)\nprint('3번: %-20f' %a)\nprint('4번: %0.2f' %a)\nprint('5번: %20.3f' %a)\nprint('6번: %-20.3f' %a)\n```\n\n💡 숫자 → 전체 자릿수, 0 → 빈자리 0채움, - → 왼쪽 정렬, .N → 소수점 N자리",
        "examples": [{"input": "", "output": "1번:             3.141592\n2번: 0000000000003.141592\n3번: 3.141592           \n4번: 3.14\n5번:                3.142\n6번: 3.142              "}],
        "test_cases": [{"input": "", "output": "1번:             3.141592\n2번: 0000000000003.141592\n3번: 3.141592           \n4번: 3.14\n5번:                3.142\n6번: 3.142              "}],
        "hint": "코드를 그대로 입력하고 실행해보세요. 각 줄의 출력 결과 차이를 비교해보세요!",
        "starter_code": "a = 3.141592\n# 위 6줄의 print 코드를 작성하세요\n",
    },
    # ── 05단원: print 함수 활용 (sep, end) ───────────────────────
    {
        "id": 46,
        "title": "시:분:초 출력 (sep 활용)",
        "category": "print 함수",
        "difficulty": "쉬움",
        "description": "시(8), 분(48), 초(27)을 변수 `a, b, c`에 저장한 후, `sep=':'`을 활용하여 출력하세요.\n\n```\n8:48:27\n```",
        "examples": [{"input": "", "output": "8:48:27"}],
        "test_cases": [{"input": "", "output": "8:48:27"}],
        "hint": "print(a, b, c, sep=':') 형식으로 sep 매개변수를 사용하세요.",
        "starter_code": "a = 8\nb = 48\nc = 27\n# sep=':'를 사용해서 출력하세요\n",
    },
    {
        "id": 47,
        "title": "날짜 출력 (sep 활용)",
        "category": "print 함수",
        "difficulty": "쉬움",
        "description": "연(2024), 월(8), 일(12)을 변수 `i, j, k`에 저장한 후, `sep='-'`를 활용하여 출력하세요.\n\n```\n2024-8-12\n```",
        "examples": [{"input": "", "output": "2024-8-12"}],
        "test_cases": [{"input": "", "output": "2024-8-12"}],
        "hint": "print(i, j, k, sep='-') 형식으로 사용하세요.",
        "starter_code": "i = 2024\nj = 8\nk = 12\n# sep='-'를 사용해서 출력하세요\n",
    },
    {
        "id": 48,
        "title": "이어서 출력하기 (end 활용)",
        "category": "print 함수",
        "difficulty": "쉬움",
        "description": "`print('아이스크림')`과 `print('주세요')`를 사용하되, 가운데 `' 많이 '`가 들어가도록 `end`를 활용하세요.\n\n```\n아이스크림 많이 주세요\n```",
        "examples": [{"input": "", "output": "아이스크림 많이 주세요"}],
        "test_cases": [{"input": "", "output": "아이스크림 많이 주세요"}],
        "hint": "print('아이스크림', end=' 많이 ')로 줄바꿈 대신 원하는 문자를 출력할 수 있습니다.",
        "starter_code": "print('아이스크림', end=' 많이 ')\n# 두 번째 print를 작성하세요\n",
    },
    {
        "id": 49,
        "title": "^ 구분자로 이어서 출력 (end 활용)",
        "category": "print 함수",
        "difficulty": "쉬움",
        "description": "`print('오늘')`, `print('날씨는')`, `print('맑음')`을 사용하되, `end`를 활용하여 `^`를 구분자로 한 줄에 출력하세요.\n\n```\n오늘^날씨는^맑음\n```",
        "examples": [{"input": "", "output": "오늘^날씨는^맑음"}],
        "test_cases": [{"input": "", "output": "오늘^날씨는^맑음"}],
        "hint": "print('오늘', end='^')처럼 end에 '^'를 사용하면 줄바꿈 대신 ^가 출력됩니다.",
        "starter_code": "print('오늘', end='^')\nprint('날씨는', end='^')\n# 마지막 print를 작성하세요\n",
    },
    # ── 응용 문제 ─────────────────────────────────────────────────
    {
        "id": 50,
        "title": "응용1: 세 줄 출력",
        "category": "응용",
        "difficulty": "쉬움",
        "description": "다음을 출력하세요.\n\n```\n프로그래밍\n정복\n시작해보자\n```",
        "examples": [{"input": "", "output": "프로그래밍\n정복\n시작해보자"}],
        "test_cases": [{"input": "", "output": "프로그래밍\n정복\n시작해보자"}],
        "hint": "print()를 3번 사용하거나, \\n 이스케이프를 활용하세요.",
        "starter_code": "# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 51,
        "title": "응용2: 특수문자 문자열 출력",
        "category": "응용",
        "difficulty": "보통",
        "description": '다음을 출력하세요. (첫 글자는 큰따옴표 `"`, 마지막 글자는 작은따옴표 `\'`)\n\n```\n"!@#$%^&*()\'\n```',
        "examples": [{"input": "", "output": '"!@#$%^&*()\''}],
        "test_cases": [{"input": "", "output": '"!@#$%^&*()\''}],
        "hint": "큰따옴표와 작은따옴표를 섞어 사용하거나 이스케이프 문자를 활용하세요.",
        "starter_code": "# 여기에 코드를 작성하세요\n",
    },
    {
        "id": 52,
        "title": "응용3: 이름과 나이 출력",
        "category": "응용",
        "difficulty": "쉬움",
        "description": "변수 `name`에 `'홍길동'`, `age`에 `30`을 저장한 후, 다음과 같이 출력하세요.\n\n```\n나는 홍길동이고, 나이는 30살이야!\n```",
        "examples": [{"input": "", "output": "나는 홍길동이고, 나이는 30살이야!"}],
        "test_cases": [{"input": "", "output": "나는 홍길동이고, 나이는 30살이야!"}],
        "hint": "print('나는 %s이고, 나이는 %d살이야!' %(name, age)) 형식으로 출력하세요.",
        "starter_code": "name = '홍길동'\nage = 30\n# 포맷 코드를 사용해서 출력하세요\n",
    },
    {
        "id": 53,
        "title": "응용4: 변수 자료형 확인",
        "category": "응용",
        "difficulty": "쉬움",
        "description": "변수 `test`에 `'대현고'`를 저장한 후, `type()` 함수를 사용하여 자료형을 출력하세요.\n\n```\n<class 'str'>\n```",
        "examples": [{"input": "", "output": "<class 'str'>"}],
        "test_cases": [{"input": "", "output": "<class 'str'>"}],
        "hint": "test = '대현고' 로 저장하고 print(type(test))로 출력하세요.",
        "starter_code": "# test에 '대현고'를 저장하고 자료형을 출력하세요\n",
    },
    {
        "id": 54,
        "title": "응용5: 나비야 노래 출력 (변수 활용)",
        "category": "응용",
        "difficulty": "보통",
        "description": "변수 `n`에 `'나비'`를 저장한 후, 변수를 활용하여 다음을 출력하세요.\n\n```\n나비야 나비야 이리 날아오너라\n노란나비 흰나비 춤을 추며 오너라\n```\n\n💡 변수 `n`을 포맷 코드나 f-string으로 활용하세요!",
        "examples": [{"input": "", "output": "나비야 나비야 이리 날아오너라\n노란나비 흰나비 춤을 추며 오너라"}],
        "test_cases": [{"input": "", "output": "나비야 나비야 이리 날아오너라\n노란나비 흰나비 춤을 추며 오너라"}],
        "hint": "print('%s야 %s야 이리 날아오너라' %(n, n)) 형식으로 출력하세요.",
        "starter_code": "n = '나비'\n# 변수 n을 활용해서 두 줄을 출력하세요\n",
    },
    {
        "id": 55,
        "title": "응용6: 나눗셈 결과 소수점 2자리 출력",
        "category": "응용",
        "difficulty": "보통",
        "description": "5를 3으로 나눈 값(`5/3`)을 변수 `a`에 저장하고, **소수점 둘째 자리까지** 출력하세요.\n\n```\n1.67\n```",
        "examples": [{"input": "", "output": "1.67"}],
        "test_cases": [{"input": "", "output": "1.67"}],
        "hint": "a = 5/3 으로 저장하고, print('%.2f' %a) 형식으로 출력하세요.",
        "starter_code": "# 5를 3으로 나눈 값을 변수 a에 저장하고 소수점 2자리 출력\n",
    },
    # ── 도전 문제: 아스키코드 ────────────────────────────────────
    {
        "id": 56,
        "title": "도전1: 문자의 아스키 코드 값 출력",
        "category": "도전",
        "difficulty": "어려움",
        "description": "문자 하나를 입력받아, 해당 문자의 **아스키 코드 값(정수)**을 출력하세요.\n\n```\n# 입력 예시\na\n# 출력 예시\n97\n```\n\n💡 `ord()` 함수를 사용하면 문자 → 숫자로 변환할 수 있습니다.\n```python\nprint(ord('a'))  # → 97\n```",
        "examples": [
            {"input": "a", "output": "97"},
            {"input": "A", "output": "65"},
        ],
        "test_cases": [
            {"input": "a", "output": "97"},
            {"input": "A", "output": "65"},
            {"input": "z", "output": "122"},
            {"input": "0", "output": "48"},
        ],
        "hint": "c = input() 으로 문자를 받고, print(ord(c)) 로 아스키 값을 출력하세요.",
        "starter_code": "c = input()\n# ord() 함수를 사용해서 아스키 코드 값을 출력하세요\n",
    },
    {
        "id": 57,
        "title": "도전2: 아스키 코드 값으로 문자 출력",
        "category": "도전",
        "difficulty": "어려움",
        "description": "정수를 입력받아, 해당 아스키 코드에 해당하는 **문자**를 출력하세요.\n\n```\n# 입력 예시\n97\n# 출력 예시\na\n```\n\n💡 `chr()` 함수를 사용하면 숫자 → 문자로 변환할 수 있습니다.\n```python\nprint(chr(97))  # → a\n```",
        "examples": [
            {"input": "97", "output": "a"},
            {"input": "65", "output": "A"},
        ],
        "test_cases": [
            {"input": "97", "output": "a"},
            {"input": "65", "output": "A"},
            {"input": "66", "output": "B"},
            {"input": "48", "output": "0"},
        ],
        "hint": "n = int(input()) 으로 숫자를 받고, print(chr(n)) 으로 문자를 출력하세요.",
        "starter_code": "n = int(input())\n# chr() 함수를 사용해서 문자를 출력하세요\n",
    },
    {
        "id": 58,
        "title": "도전3: 나만의 암호 만들기 (+2 이동 암호화)",
        "category": "도전",
        "difficulty": "어려움",
        "description": "문자열을 입력받아, 각 문자의 아스키 코드를 **+2** 이동시켜 암호화하여 출력하세요.\n\n```\n# 입력 예시\nLove\n# 출력 예시\nNqxg\n```\n\n💡 힌트 코드 구조:\n```python\na = input()\nb = ''\nfor i in a:\n    b = b + chr(ord(i) + 2)\nprint(b)\n```",
        "examples": [
            {"input": "Love", "output": "Nqxg"},
            {"input": "Hello", "output": "Jgnnq"},
        ],
        "test_cases": [
            {"input": "Love", "output": "Nqxg"},
            {"input": "Hello", "output": "Jgnnq"},
            {"input": "abc", "output": "cde"},
            {"input": "Python", "output": "Ravjqp"},
        ],
        "hint": "for문으로 각 문자를 순회하며, chr(ord(문자) + 2)로 암호화하세요.",
        "starter_code": "a = input()\nb = ''\nfor i in a:\n    # 각 문자를 +2 이동시켜 b에 추가하세요\n    pass\nprint(b)\n",
    },
]
